// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	v1alpha11 "github.com/ironcore-dev/lifecycle-manager/api/lifecycle/v1alpha1"
	v1alpha1 "github.com/ironcore-dev/lifecycle-manager/lcmi/api/common/v1alpha1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListMachinesRequest struct {
	Filter               *v1alpha1.Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListMachinesRequest) Reset()         { *m = ListMachinesRequest{} }
func (m *ListMachinesRequest) String() string { return proto.CompactTextString(m) }
func (*ListMachinesRequest) ProtoMessage()    {}
func (*ListMachinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *ListMachinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMachinesRequest.Unmarshal(m, b)
}
func (m *ListMachinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMachinesRequest.Marshal(b, m, deterministic)
}
func (m *ListMachinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMachinesRequest.Merge(m, src)
}
func (m *ListMachinesRequest) XXX_Size() int {
	return xxx_messageInfo_ListMachinesRequest.Size(m)
}
func (m *ListMachinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMachinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMachinesRequest proto.InternalMessageInfo

func (m *ListMachinesRequest) GetFilter() *v1alpha1.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListMachinesResponse struct {
	Machines             []*v1alpha11.Machine `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListMachinesResponse) Reset()         { *m = ListMachinesResponse{} }
func (m *ListMachinesResponse) String() string { return proto.CompactTextString(m) }
func (*ListMachinesResponse) ProtoMessage()    {}
func (*ListMachinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *ListMachinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMachinesResponse.Unmarshal(m, b)
}
func (m *ListMachinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMachinesResponse.Marshal(b, m, deterministic)
}
func (m *ListMachinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMachinesResponse.Merge(m, src)
}
func (m *ListMachinesResponse) XXX_Size() int {
	return xxx_messageInfo_ListMachinesResponse.Size(m)
}
func (m *ListMachinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMachinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMachinesResponse proto.InternalMessageInfo

func (m *ListMachinesResponse) GetMachines() []*v1alpha11.Machine {
	if m != nil {
		return m.Machines
	}
	return nil
}

type ScanRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ScanResponse struct {
	Response             *v1alpha11.MachineStatus `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetResponse() *v1alpha11.MachineStatus {
	if m != nil {
		return m.Response
	}
	return nil
}

type InstallRequest struct {
	Name                 string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string                      `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Packages             []*v1alpha11.PackageVersion `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InstallRequest) Reset()         { *m = InstallRequest{} }
func (m *InstallRequest) String() string { return proto.CompactTextString(m) }
func (*InstallRequest) ProtoMessage()    {}
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}
func (m *InstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallRequest.Unmarshal(m, b)
}
func (m *InstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallRequest.Marshal(b, m, deterministic)
}
func (m *InstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallRequest.Merge(m, src)
}
func (m *InstallRequest) XXX_Size() int {
	return xxx_messageInfo_InstallRequest.Size(m)
}
func (m *InstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallRequest proto.InternalMessageInfo

func (m *InstallRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstallRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InstallRequest) GetPackages() []*v1alpha11.PackageVersion {
	if m != nil {
		return m.Packages
	}
	return nil
}

type InstallResponse struct {
	Result               v1alpha1.InstallResult `protobuf:"varint,1,opt,name=result,proto3,enum=github.com.ironcore_dev.lifecycle_manager.lcmi.api.common.v1alpha1.InstallResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *InstallResponse) Reset()         { *m = InstallResponse{} }
func (m *InstallResponse) String() string { return proto.CompactTextString(m) }
func (*InstallResponse) ProtoMessage()    {}
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}
func (m *InstallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallResponse.Unmarshal(m, b)
}
func (m *InstallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallResponse.Marshal(b, m, deterministic)
}
func (m *InstallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallResponse.Merge(m, src)
}
func (m *InstallResponse) XXX_Size() int {
	return xxx_messageInfo_InstallResponse.Size(m)
}
func (m *InstallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallResponse proto.InternalMessageInfo

func (m *InstallResponse) GetResult() v1alpha1.InstallResult {
	if m != nil {
		return m.Result
	}
	return v1alpha1.InstallResult_INSTALL_RESULT_UNSPECIFIED
}

func init() {
	proto.RegisterType((*ListMachinesRequest)(nil), "github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.ListMachinesRequest")
	proto.RegisterType((*ListMachinesResponse)(nil), "github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.ListMachinesResponse")
	proto.RegisterType((*ScanRequest)(nil), "github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.ScanResponse")
	proto.RegisterType((*InstallRequest)(nil), "github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.InstallRequest")
	proto.RegisterType((*InstallResponse)(nil), "github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.InstallResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x09, 0x9b, 0x4a, 0xeb, 0x4e, 0x45, 0x32, 0x1c, 0xaa, 0x88, 0xc3, 0x94, 0xd3, 0x2e,
	0x73, 0xb4, 0xc2, 0x81, 0x1b, 0x12, 0x13, 0x48, 0x43, 0x43, 0x74, 0x29, 0x42, 0xc0, 0x65, 0x72,
	0xdd, 0xb7, 0xd4, 0xaa, 0x63, 0x07, 0xdb, 0x89, 0x54, 0x01, 0x7f, 0x12, 0x12, 0x27, 0xee, 0x1c,
	0xf8, 0xbf, 0x50, 0x12, 0xc7, 0xd9, 0x04, 0x07, 0x28, 0xe1, 0x54, 0xeb, 0x55, 0xfe, 0x7d, 0xdf,
	0xfb, 0xf2, 0xfc, 0xd0, 0x88, 0xe6, 0x9c, 0xe4, 0x5a, 0x59, 0x85, 0x4f, 0x53, 0x6e, 0xd7, 0xc5,
	0x92, 0x30, 0x95, 0x11, 0xae, 0x95, 0x64, 0x4a, 0xc3, 0xe5, 0x0a, 0x4a, 0x22, 0xf8, 0x15, 0xb0,
	0x2d, 0x13, 0x70, 0x99, 0x51, 0x49, 0x53, 0xd0, 0x44, 0xb0, 0x8c, 0x93, 0xea, 0x66, 0x46, 0xd9,
	0x9a, 0x4b, 0x20, 0xe5, 0x09, 0x15, 0xf9, 0x9a, 0x9e, 0x84, 0xf3, 0x0e, 0x12, 0xb7, 0x90, 0xe3,
	0x15, 0x94, 0xb1, 0x87, 0x1c, 0x3b, 0x48, 0x4c, 0x73, 0xde, 0x55, 0xe3, 0x96, 0x10, 0xa7, 0x20,
	0x41, 0x53, 0x0b, 0xab, 0xc6, 0x56, 0x78, 0xfe, 0xe7, 0xc4, 0xca, 0x56, 0x8d, 0x65, 0x2a, 0xcb,
	0x94, 0xec, 0x98, 0xbe, 0xc9, 0xf0, 0xd1, 0xe6, 0xb1, 0x21, 0x5c, 0x55, 0x15, 0xe7, 0x5d, 0x6f,
	0xe3, 0x7c, 0x93, 0x56, 0x05, 0x13, 0x67, 0x60, 0x69, 0x5c, 0xfe, 0xe2, 0x21, 0xda, 0xa2, 0x7b,
	0xe7, 0xdc, 0xd8, 0x97, 0xcd, 0x0d, 0x93, 0xc0, 0x87, 0x02, 0x8c, 0xc5, 0x4b, 0x34, 0xb8, 0xe2,
	0xc2, 0x82, 0x9e, 0x06, 0x87, 0xc1, 0xd1, 0x78, 0xf6, 0x82, 0xec, 0x10, 0x61, 0xe3, 0xd5, 0x27,
	0x48, 0x9e, 0xd7, 0xc4, 0xc4, 0x91, 0xa3, 0xcf, 0xe8, 0xfe, 0x4d, 0x69, 0x93, 0x2b, 0x69, 0x00,
	0x03, 0x1a, 0xba, 0x06, 0xcc, 0x34, 0x38, 0xdc, 0x3b, 0x1a, 0xcf, 0xce, 0xfe, 0x42, 0xbd, 0x12,
	0xf6, 0xd5, 0x4e, 0xdb, 0xa9, 0x24, 0x1e, 0x1d, 0x3d, 0x41, 0xe3, 0x05, 0xa3, 0xb2, 0xed, 0x18,
	0xa3, 0x7d, 0x49, 0x33, 0xa8, 0xfb, 0x1d, 0x25, 0xf5, 0x19, 0x3f, 0x40, 0xa3, 0xea, 0xd7, 0xe4,
	0x94, 0xc1, 0xf4, 0x76, 0xfd, 0x47, 0x57, 0x88, 0x3e, 0xa2, 0x83, 0x06, 0xe0, 0x7c, 0x6f, 0xd0,
	0x50, 0xbb, 0xb3, 0x4b, 0xed, 0x55, 0x6f, 0xbe, 0x17, 0x96, 0xda, 0xc2, 0x24, 0x5e, 0x20, 0xfa,
	0x1a, 0xa0, 0xc9, 0x99, 0x34, 0x96, 0x0a, 0xb1, 0x73, 0x07, 0x58, 0xa0, 0x61, 0x4e, 0xd9, 0x86,
	0xa6, 0x60, 0xa6, 0x7b, 0x75, 0xd2, 0xf3, 0x7f, 0x77, 0x3c, 0x6f, 0x88, 0x6f, 0x40, 0x1b, 0xae,
	0x64, 0xe2, 0x15, 0xa2, 0x4f, 0xe8, 0xae, 0x77, 0xec, 0x22, 0xe3, 0x68, 0xa0, 0xc1, 0x14, 0xc2,
	0xd6, 0xa6, 0x27, 0xb3, 0x8b, 0x3e, 0xc6, 0xac, 0x13, 0x29, 0x84, 0x4d, 0x9c, 0xc0, 0xec, 0xfb,
	0x3e, 0x9a, 0xb4, 0x61, 0x82, 0x2e, 0x39, 0x03, 0xfc, 0x23, 0x40, 0x07, 0xd7, 0x27, 0x10, 0xbf,
	0x25, 0x3d, 0x2c, 0x0a, 0xf2, 0x9b, 0xf7, 0x14, 0xbe, 0xfb, 0x0f, 0x64, 0x37, 0x09, 0xb7, 0xf0,
	0x97, 0x00, 0xed, 0x57, 0x93, 0x88, 0xe7, 0xbd, 0xa8, 0x5c, 0x7b, 0x15, 0xe1, 0x45, 0x8f, 0x44,
	0xef, 0xf7, 0x5b, 0x80, 0xee, 0xb8, 0x8f, 0x84, 0x17, 0xbd, 0x08, 0xdc, 0x7c, 0x09, 0xe1, 0xeb,
	0x7e, 0xa1, 0xad, 0xf1, 0xa7, 0xcf, 0xde, 0x9f, 0xee, 0xb0, 0xb2, 0x1d, 0xd8, 0xef, 0xec, 0xe5,
	0xa0, 0x5e, 0xbd, 0x0f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x98, 0x54, 0x64, 0x6a, 0xa2, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MachineServiceClient is the client API for MachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineServiceClient interface {
	ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error)
}

type machineServiceClient struct {
	cc *grpc.ClientConn
}

func NewMachineServiceClient(cc *grpc.ClientConn) MachineServiceClient {
	return &machineServiceClient{cc}
}

func (c *machineServiceClient) ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error) {
	out := new(ListMachinesResponse)
	err := c.cc.Invoke(ctx, "/github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.MachineService/ListMachines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.MachineService/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error) {
	out := new(InstallResponse)
	err := c.cc.Invoke(ctx, "/github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.MachineService/Install", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineServiceServer is the server API for MachineService service.
type MachineServiceServer interface {
	ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	Install(context.Context, *InstallRequest) (*InstallResponse, error)
}

// UnimplementedMachineServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMachineServiceServer struct {
}

func (*UnimplementedMachineServiceServer) ListMachines(ctx context.Context, req *ListMachinesRequest) (*ListMachinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMachines not implemented")
}
func (*UnimplementedMachineServiceServer) Scan(ctx context.Context, req *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (*UnimplementedMachineServiceServer) Install(ctx context.Context, req *InstallRequest) (*InstallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Install not implemented")
}

func RegisterMachineServiceServer(s *grpc.Server, srv MachineServiceServer) {
	s.RegisterService(&_MachineService_serviceDesc, srv)
}

func _MachineService_ListMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMachinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).ListMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.MachineService/ListMachines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).ListMachines(ctx, req.(*ListMachinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.MachineService/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_Install_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).Install(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.MachineService/Install",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).Install(ctx, req.(*InstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MachineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.ironcore_dev.lifecycle_manager.lcmi.api.machine.v1alpha1.MachineService",
	HandlerType: (*MachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMachines",
			Handler:    _MachineService_ListMachines_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _MachineService_Scan_Handler,
		},
		{
			MethodName: "Install",
			Handler:    _MachineService_Install_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
