apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lifecycle-service
    app.kubernetes.io/part-of: lifecycle-service
    app.kubernetes.io/managed-by: kustomize
  name: service-sa
  namespace: system
