---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - machines
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - machinetypes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - machinetypes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - updatejobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - updatejobs/status
  verbs:
  - get
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - updatetasks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.ironcore.dev
  resources:
  - updatetasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - onmetal.de
  resources:
  - oobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - onmetal.de
  resources:
  - oobs/status
  verbs:
  - get
