// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PackageVersionApplyConfiguration represents an declarative configuration of the PackageVersion type for use
// with apply.
type PackageVersionApplyConfiguration struct {
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// PackageVersionApplyConfiguration constructs an declarative configuration of the PackageVersion type for use with
// apply.
func PackageVersion() *PackageVersionApplyConfiguration {
	return &PackageVersionApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PackageVersionApplyConfiguration) WithName(value string) *PackageVersionApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *PackageVersionApplyConfiguration) WithVersion(value string) *PackageVersionApplyConfiguration {
	b.Version = &value
	return b
}
