apiVersion: lifecycle.ironcore.dev/v1alpha1
kind: Machine
metadata:
  labels:
    app.kubernetes.io/name: machine
    app.kubernetes.io/instance: machine-sample
    app.kubernetes.io/part-of: lifecycle-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lifecycle-manager
  name: machine-sample
spec:
  # TODO(user): Add fields here
