//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwarePackage) DeepCopyInto(out *FirmwarePackage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwarePackage.
func (in *FirmwarePackage) DeepCopy() *FirmwarePackage {
	if in == nil {
		return nil
	}
	out := new(FirmwarePackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwarePackage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwarePackageList) DeepCopyInto(out *FirmwarePackageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FirmwarePackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwarePackageList.
func (in *FirmwarePackageList) DeepCopy() *FirmwarePackageList {
	if in == nil {
		return nil
	}
	out := new(FirmwarePackageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwarePackageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwarePackageSpec) DeepCopyInto(out *FirmwarePackageSpec) {
	*out = *in
	out.MachineTypeRef = in.MachineTypeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwarePackageSpec.
func (in *FirmwarePackageSpec) DeepCopy() *FirmwarePackageSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwarePackageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwarePackageStatus) DeepCopyInto(out *FirmwarePackageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwarePackageStatus.
func (in *FirmwarePackageStatus) DeepCopy() *FirmwarePackageStatus {
	if in == nil {
		return nil
	}
	out := new(FirmwarePackageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineLifecycle) DeepCopyInto(out *MachineLifecycle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineLifecycle.
func (in *MachineLifecycle) DeepCopy() *MachineLifecycle {
	if in == nil {
		return nil
	}
	out := new(MachineLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineLifecycle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineLifecycleList) DeepCopyInto(out *MachineLifecycleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineLifecycle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineLifecycleList.
func (in *MachineLifecycleList) DeepCopy() *MachineLifecycleList {
	if in == nil {
		return nil
	}
	out := new(MachineLifecycleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineLifecycleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineLifecycleSpec) DeepCopyInto(out *MachineLifecycleSpec) {
	*out = *in
	out.MachineTypeRef = in.MachineTypeRef
	out.OOBMachineRef = in.OOBMachineRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineLifecycleSpec.
func (in *MachineLifecycleSpec) DeepCopy() *MachineLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(MachineLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineLifecycleStatus) DeepCopyInto(out *MachineLifecycleStatus) {
	*out = *in
	in.LastScanTime.DeepCopyInto(&out.LastScanTime)
	if in.InstalledPackages != nil {
		in, out := &in.InstalledPackages, &out.InstalledPackages
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineLifecycleStatus.
func (in *MachineLifecycleStatus) DeepCopy() *MachineLifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(MachineLifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineType) DeepCopyInto(out *MachineType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineType.
func (in *MachineType) DeepCopy() *MachineType {
	if in == nil {
		return nil
	}
	out := new(MachineType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineTypeList) DeepCopyInto(out *MachineTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineTypeList.
func (in *MachineTypeList) DeepCopy() *MachineTypeList {
	if in == nil {
		return nil
	}
	out := new(MachineTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineTypeSpec) DeepCopyInto(out *MachineTypeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineTypeSpec.
func (in *MachineTypeSpec) DeepCopy() *MachineTypeSpec {
	if in == nil {
		return nil
	}
	out := new(MachineTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineTypeStatus) DeepCopyInto(out *MachineTypeStatus) {
	*out = *in
	in.LastScanTime.DeepCopyInto(&out.LastScanTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineTypeStatus.
func (in *MachineTypeStatus) DeepCopy() *MachineTypeStatus {
	if in == nil {
		return nil
	}
	out := new(MachineTypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineUpdateJob) DeepCopyInto(out *MachineUpdateJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineUpdateJob.
func (in *MachineUpdateJob) DeepCopy() *MachineUpdateJob {
	if in == nil {
		return nil
	}
	out := new(MachineUpdateJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineUpdateJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineUpdateJobList) DeepCopyInto(out *MachineUpdateJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineUpdateJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineUpdateJobList.
func (in *MachineUpdateJobList) DeepCopy() *MachineUpdateJobList {
	if in == nil {
		return nil
	}
	out := new(MachineUpdateJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineUpdateJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineUpdateJobSpec) DeepCopyInto(out *MachineUpdateJobSpec) {
	*out = *in
	out.MachineLifecycleRef = in.MachineLifecycleRef
	out.FirmwarePackageRef = in.FirmwarePackageRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineUpdateJobSpec.
func (in *MachineUpdateJobSpec) DeepCopy() *MachineUpdateJobSpec {
	if in == nil {
		return nil
	}
	out := new(MachineUpdateJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineUpdateJobStatus) DeepCopyInto(out *MachineUpdateJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineUpdateJobStatus.
func (in *MachineUpdateJobStatus) DeepCopy() *MachineUpdateJobStatus {
	if in == nil {
		return nil
	}
	out := new(MachineUpdateJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTask) DeepCopyInto(out *UpdateTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTask.
func (in *UpdateTask) DeepCopy() *UpdateTask {
	if in == nil {
		return nil
	}
	out := new(UpdateTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdateTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTaskList) DeepCopyInto(out *UpdateTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpdateTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTaskList.
func (in *UpdateTaskList) DeepCopy() *UpdateTaskList {
	if in == nil {
		return nil
	}
	out := new(UpdateTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdateTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTaskSpec) DeepCopyInto(out *UpdateTaskSpec) {
	*out = *in
	out.MachineTypeRef = in.MachineTypeRef
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Machines != nil {
		in, out := &in.Machines, &out.Machines
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTaskSpec.
func (in *UpdateTaskSpec) DeepCopy() *UpdateTaskSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTaskStatus) DeepCopyInto(out *UpdateTaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTaskStatus.
func (in *UpdateTaskStatus) DeepCopy() *UpdateTaskStatus {
	if in == nil {
		return nil
	}
	out := new(UpdateTaskStatus)
	in.DeepCopyInto(out)
	return out
}
