---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  namespace: system
  labels:
    control-plane: lifecycle-service
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: lifecycle-service
    app.kubernetes.io/part-of: lifecycle-service
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: lifecycle-service
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: lifecycle-service
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: controller:latest
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /manager
          args:
            - --namespace=POD_NAMESPACE
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      serviceAccountName: service-sa
